# Generated by Django 4.2.3 on 2023-08-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d', verbose_name='Фото')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('status', models.CharField(choices=[(1, 'Ожидание подтверждения'), (2, 'Запрос принят'), (3, 'Детали обмена согласованы'), (4, 'Обмен завершен'), (5, 'Отклонен'), (6, 'Отменен')], default=1)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
