# Generated by Django 4.2.3 on 2023-08-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d', verbose_name='Фото')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('status', models.CharField(choices=[('Ожидание подтверждения', 'Ожидание подтверждения'), ('Запрос принят', 'Запрос принят'), ('Детали обмена согласованы', 'Детали обмена согласованы'), ('Обмен завершен', 'Обмен завершен'), ('Отклонен', 'Отклонен'), ('Отменен', 'Отменен')], default=1, max_length=500)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
