# Generated by Django 4.2.3 on 2023-08-30 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название книги')),
                ('image', models.ImageField(upload_to='posts/%Y/%m/%d', verbose_name='Фото')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('author', models.CharField(max_length=100, null=True, verbose_name='Автор книги')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='PostExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Ожидание подтверждения', 'Ожидание подтверждения'), ('Запрос принят', 'Запрос принят'), ('Детали обмена согласованы', 'Детали обмена согласованы'), ('Обмен завершен', 'Обмен завершен'), ('Отклонен', 'Отклонен'), ('Отменен', 'Отменен')], default=1, max_length=500, verbose_name='Cтатус')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('post_offered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.posts', verbose_name='Предлагается')),
                ('post_requested', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to='posts.posts', verbose_name='Запрашивается')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_received', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges_sent', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Запрос на обмен',
                'verbose_name_plural': 'Запросы на обмен',
            },
        ),
    ]
