# Generated by Django 4.2.3 on 2023-08-25 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_posts_userprofile_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='UserProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostUser', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
