# Generated by Django 4.2.3 on 2023-08-25 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_posts_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='UserProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserProfile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
